name: MTT-Net
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda-version=11.8
  - matplotlib
  - ml-collections
  - numpy
  - pandas
  - pip
  - pydicom
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - pywavelets
  - scikit-image
  - scikit-learn
  - scipy
  - simpleitk
  - tensorboardx
  - timm
  - torchtriton
  - torchvision
  - tqdm
  - pip:
      - pytorch-wavelets
      - torch-tb-profiler
